// Object holding error messages
const ERROR = {
  INVALID_LABEL: { code: 1, msg: 'THE LABEL PROVIDED FOR AN INSTRUCTION IS MALFORMED' },
  INVALID_VAR: { code: 2, msg: 'THE VARIABLE PROVIDED FOR AN INSTRUCTION IS MALFORMED' },
  INVALID_NUM: { code: 3, msg: 'THE NUMBER PROVIDED IS NOT ACTUALLY A NUMBER' },
  INVALID_STR: { code: 4, msg: 'THE STRING PROVIDED IS NOT ACTUALLY A STRING' },
  INVALID_OPER: { code: 5, msg: 'THERE IS NO COMMAND IN THE STRING' },
  INVALID_INSTRUCTION: { code: 6, msg: 'PARAMETERS PASSED ARE NOT AN INSTRUCTION' },
};